db_file: "bot.db"

bot_url: "https://t.me/pocket_on_helper_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    alrady_authorized: "Ты уже авторизирован. Присылай ссылку, а я ее сохраню."
    saved_successfully: "Ссылка успешно сохранена!"
    unknown_command: "Я не знаю такой команды :("
  errors:
    default: "Произошла неизвестаня ошибка."
    invalid_url: "Это невальдная ссылка!"
    unauthorized: "Ты не авторизован! Используй команду /start."
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуй ещё раз позже."